version: '2.4'

services:
  web:
    image: nosqli-labs
    hostname: nosqliweb
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nosqli-network
    ports:
      - "8080:80"
    platform: linux/amd64
  mongo:
    container_name: nosqli-mongodb
    image: mongo:3.4.1
    networks:
      - nosqli-network
    ports:
      - "27017:27017"
    platform: linux/amd64

networks:
  nosqli-network:
    driver: bridge
